services:
  db:
    image: ankane/pgvector:latest
    container_name: catlovers_db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: array
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: catlovers_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: